language: cpp

before_install:
    - sudo apt-get -qq update
install:
    - wget https://kulshanconcepts.com/files/cross-20160214.tgz -nv -nc
    - sudo tar -xzf cross-20160214.tgz -C /opt
script:
    - bash build-ci.sh
