ROOT_DIR:=$(shell dirname $(realpath $(lastword $(MAKEFILE_LIST))))
ifeq ($(CI_BUILD),yes)
BINPREFIX:=/opt/cross/bin/arm-none-eabi-
else
BINPREFIX:=$(ROOT_DIR)/../bin/arm-none-eabi-
endif

AR=$(BINPREFIX)ar
CC=$(BINPREFIX)gcc
CXX=$(BINPREFIX)g++
OBJCOPY=$(BINPREFIX)objcopy
CFLAGS=-mcpu=cortex-a7 -mfpu=vfpv4 -fpic -ffreestanding -std=gnu99 -Wall -Wextra
CXXFLAGS=-mcpu=cortex-a7 -mfpu=vfpv4 -fpic -ffreestanding -std=c++11 -Wall -Wextra
